# STRICTLY A SOCIAL MEDIA PLATFORM
# Intellectual Property & Artistic Inspiration
# Legal & Ethical Safeguards
[theme]
# Custom professional palette for the Streamlit app
base = "dark"
primaryColor = "#0A84FF"
backgroundColor = "#1e1e1e"
secondaryBackgroundColor = "#1e1e1e"
textColor = "#f0f0f0"
font = "Iosevka"