# STRICTLY A SOCIAL MEDIA PLATFORM
# Intellectual Property & Artistic Inspiration
# Legal & Ethical Safeguards
[theme]
primaryColor="#2A7AE2"
backgroundColor="#F3F4F6"
secondaryBackgroundColor="#FFFFFF"
textColor="#111827"
font="sans serif"
