# STRICTLY A SOCIAL MEDIA PLATFORM
# Intellectual Property & Artistic Inspiration
# Legal & Ethical Safeguards
[theme]
# Custom professional palette for the Streamlit app
primaryColor = "#4A90E2"
backgroundColor = "#181818"
secondaryBackgroundColor = "#242424"
textColor = "#E8E6E3"
font = "monospace"
