# STRICTLY A SOCIAL MEDIA PLATFORM
# Intellectual Property & Artistic Inspiration
# Legal & Ethical Safeguards
[theme]
primaryColor="#4A90E2"
backgroundColor="#F0F2F6"
secondaryBackgroundColor="#FFFFFF"
textColor="#333333"
font="sans serif"
