# STRICTLY A SOCIAL MEDIA PLATFORM
# Intellectual Property & Artistic Inspiration
# Legal & Ethical Safeguards
[theme]
# Default Codex-inspired dark palette
primaryColor = "#19C37D"
backgroundColor = "#202123"
secondaryBackgroundColor = "#343541"
textColor = "#ECECF1"
font = "monospace"
