# STRICTLY A SOCIAL MEDIA PLATFORM
# Intellectual Property & Artistic Inspiration
# Legal & Ethical Safeguards
[theme]
# Custom professional palette for the Streamlit app
primaryColor = "#0A84FF"
backgroundColor = "#F0F2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"
font = "sans serif"
