# STRICTLY A SOCIAL MEDIA PLATFORM
# Intellectual Property & Artistic Inspiration
# Legal & Ethical Safeguards
[theme]
base = "dark"
primaryColor = "#00D2FF"
backgroundColor = "#0a0a0a"
secondaryBackgroundColor = "#1a1a1a"
textColor = "#ffffff"
font = "Inter, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif"

